### PR TITLE
Ticket Forms.

### PR DESCRIPTION
**Pull request by nkilian**
* Added ticket_forms specification.
* Updated doc_dict with missing fields
* Added ticket_forms to endpoint, mapping and Zenpy.

#26

### CODE REVIEW

**Comment by nkilian** [comment]
* Omitted changed api_objects files.
The class order in the files is much changed in my generated files after adding ticket_forms, not sure if this is expected behaviour or if there is a way to control the order? It means any diff is almost useless.

* Updated doc_dict with missing fields
Not sure if this file is auto-generated from the Zendesk documentation? The fields I added are also missing from the Zendesk documentation, but are included in the response.

**Comment by nkilian** [comment]
CI failing as I have omitted api_objects files.

**Comment by facetoe** [comment]
Thanks for the PR @nkilian, looks good. I've fixed the ordering issue in master so you should be able to generate the objects without thrashing the diff.

**Comment by nkilian** [comment]
All done.

**Comment by facetoe** [comment]
Excellent, thanks!

**Pull request merged**
