### PR TITLE
Add incremental calls api

### PR DESCRIPTION
**Pull request by NiallRees**
Adds the incremental calls api: https://developer.zendesk.com/rest_api/docs/voice-api/incremental_exports#incremental-calls

### CODE REVIEW

**Comment by NiallRees** [comment]
@facetoe bit stuck here, I'm testing with the following:

```
import datetime
from zenpy import Zenpy


creds = {'email': "xxxxx", "token": 'xxxxx', 'subdomain': 'xxxxx'}
zenpy_client = Zenpy(**creds)
yesterday = datetime.datetime.now() - datetime.timedelta(days=1)
result_generator = zenpy_client.talk.calls.incremental(start_time=yesterday)
for result in result_generator:
    print(result)
```

and getting

```
Traceback (most recent call last):
  File "zendesk.py", line 8, in <module>
    result_generator = zenpy_client.talk.calls.incremental(start_time=yesterday)
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/api.py", line 646, in incremental
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/api.py", line 283, in _query_zendesk
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/api.py", line 112, in _get
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/api.py", line 212, in _process_response
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/response.py", line 103, in build
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/response.py", line 80, in deserialize
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/mapping.py", line 136, in object_from_json
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/api_objects/__init__.py", line 28, in __setattr__
  File "/Users/niallwoodward/dev/venvs/zenpy/lib/python3.7/site-packages/zenpy-2.0.22-py3.7.egg/zenpy/lib/api_objects/talk_objects.py", line 374, in phone_number
AttributeError: 'str' object has no attribute 'id'
```

https://github.com/facetoe/zenpy/pull/454/files#diff-9a6f0e892ca44f09040db986925cef3c097002c65ff6b6a1e1e72fbbce95b97dR371-R375

I'm struggling to debug as a result of the (very neat) auto generated classes, any ideas?

**Comment by NiallRees** [comment]
Removing phone_number_id from the call spec fixes them problem, but obviously isn't ideal as that's missing from the result now

**Comment by facetoe** [comment]
This should fix the phone number issue:

```diff
diff --git a/tools/gen_classes.py b/tools/gen_classes.py
index 8666d2f..3a0672c 100755
--- a/tools/gen_classes.py
+++ b/tools/gen_classes.py
@@ -213,7 +213,7 @@ class Attribute(object):
             return attr_name
 
     def get_attr_assignment(self, object_name, object_type, key):
-        if object_type != key and object_type != 'date' and key.endswith('_id'):
+        if object_type != key and object_type != 'date' and object_name != 'phone_number' and key.endswith('_id'):
             return '%s.id' % object_name
         elif key.endswith('_ids'):
             return '[o.id for o in %(object_name)s]' % locals()

```

**Comment by NiallRees** [comment]
Hey @facetoe thanks for looking into this. I think we're getting there, the change you suggested results in:

```
    @phone_number.setter
    def phone_number(self, phone_number):
        if phone_number:
            self.phone_number = phone_number
```

which results in records returned with `'phone_number_id': '+4420xxxxx448'` and a missing `phone_number` field. If I manually change the method to be

```
    @phone_number.setter
    def phone_number(self, phone_number):
        if phone_number:
            self._phone_number = phone_number
```

then I get the correct result of `'phone_number_id': 207xxx65` and `'phone_number': '+4420xxxxx448'` in the record. What do you reckon?

**Comment by facetoe** [comment]
Manually changing the output won't work as next time the script is run it will be clobbered.

**Comment by NiallRees** [comment]
> Manually changing the output won't work as next time the script is run it will be clobbered.

Yeah I realise, my question really is how we change the class generator to achieve that result?  Does it need a new template or just some additional logic to accommodate the phone number like you previously suggested?

**Comment by NiallRees** [comment]
Ok @facetoe I've got this working with the class generator. The shim I've put in does the job, but not sure if you think it should go somewhere else. Thanks :)

**Comment by NiallRees** [comment]
@facetoe just a bump on this if you have any ideas otherwise could we merge?

**Comment by hz-lschick** [comment]
@facetoe Any status update? Would love to see this merged.

**Pull request merged**
