### PR TITLE
Fix for #633, support for modern python, improved docs

### PR DESCRIPTION
**Pull request by keerthik**
Addresses Issue #633 and adds some other minor improvements
 
3 main changes
- added `content_tag` specification, api, mapping, endpoint for new [content tags api](https://developer.zendesk.com/api-reference/help_center/help-center-api/content_tags/).
- updated `CONTRIBUTING.md` to be more descriptive for adding new objects (as I learned how to do it)
- regenerated classes

2 minor changes
- version bump
- in `setup.cfg`, changed `description-file` -> `description_file` because `setuptools` complained

EDIT: one additional small but significant change is `gen_classes.py` execution is wrapped in `if __name__  == "__main__":` so that modern python `multiprocessing.pool` doesn't complain and fail. This class is only applicable to package development.

### CODE REVIEW

**Comment by Ptr314** [comment]
Hi @keerthik !

Thanks a lot for your contributions. I've taken a look at the code and haven't seen any disturbing things. But to be sure - have you tried to run built-in tests according to [this document](https://github.com/facetoe/zenpy/blob/master/TESTING.md)?

**Comment by keerthik** [comment]
Hi @Ptr314 

I had not, was testing just the new functionality using it as a local pip package with my own separate project till it worked.

Just now ran whatever's under recording tests:

```
make unittest
make pytest
nosetests -v --stop --exe tests/test_api/test_create_update_delete_zendesk.py
nosetests -v --stop --exe tests/test_api/test_create_update_delete_zendesk.py:TestUserCreateUpdateDelete
nosetests -v --stop --exe tests/test_api/test_create_update_delete_zendesk.py:TestUserCreateUpdateDelete.test_multiple_update_full_objects
pytest tests/test_api/test_create_update_delete_zendesk.py::TestUserCreateUpdateDelete.test_multiple_update_full_objects
```

the last one returned this error (seems to be an issue with the testing, not the api):

```error
ERROR: not found: /Users/keerthik/projects/contributions/zenpy/tests/test_api/test_create_update_delete_zendesk.py::TestUserCreateUpdateDelete.test_multiple_update_full_objects
(no match in any of [<Module test_create_update_delete_zendesk.py>])
```

i did not run tests with a live account.

**Comment by Ptr314** [comment]
Hi @keerthik !

Great work!

These are just examples. In most cases, running "make pytest" is enough.

So, if it goes well, I don't have any objections for accepring this PR. @cryptomail could you please make a release?

**Comment by cryptomail** [comment]
OK, give me a few to look at this today.  This was the first PR in a while, so it's first in the queue :)
Sorry for the delay.  Will get back to you.

**Comment by cryptomail** [comment]
hmmm interestingly enough I'm having trouble executing tests locally....will need to sort through this.

**Comment by cryptomail** [comment]
Hah and now I have CircleCI issues :). I think I have to push the stack on this in favor of moving to GHA, so it's a one stop shop anyway.  Always something interesting happening. ^_^
Pushing the stack and working on shoring some of these project issues up first unfortunately before this can go in.  Hang tight!

**Comment by cryptomail** [comment]
Your PR is now superceded by https://github.com/facetoe/zenpy/pull/642 ^_^ Let's party.  Analyzing.  PS I've decided I'll do the bump since I have a whole flow :) haha

**Comment by cryptomail** [comment]
Closing in favor of https://github.com/facetoe/zenpy/pull/642

**Pull request closed without merging**
