### PR TITLE
Failing imports in some cases

### PR DESCRIPTION
**Pull request by super-oleg**
In some cases application fails with error on imports in mapping.py.
AttributeError: module 'zenpy' has no attribute 'lib'

Moving the import out of class helps to avoid that

### CODE REVIEW

**Comment by facetoe** [comment]
Can you post a snippet that triggers the failure? 

There is a `Comment` object in both the `api_objects` and `help_centre_objects` modules, I had the full path there to differentiate between them. If it is causing issues I'll need to find another solution, especially as it is likely that implementing the NPS API will also have object namespace collisions like this. My concern with this PR is it is ambiguous which module the `Comment` class comes from.

**Comment by super-oleg** [comment]
I can't provide you the code, that triggers this.
This is the part of stacktrace:
```
  from zenpy import Zenpy
File "virtual_env/lib64/python3.6/site-packages/zenpy/__init__.py", line 6, in <module>
  from zenpy.lib.api import (
File "virtual_env/lib64/python3.6/site-packages/zenpy/lib/api.py", line 13, in <module>
  from zenpy.lib.mapping import ZendeskObjectMapping, ChatObjectMapping, HelpCentreObjectMapping
File "virtual_env/lib64/python3.6/site-packages/zenpy/lib/mapping.py", line 168, in <module>
  class HelpCentreObjectMapping(ZendeskObjectMapping):
File "virtual_env/lib64/python3.6/site-packages/zenpy/lib/mapping.py", line 174, in HelpCentreObjectMapping
  'article_attachment': zenpy.lib.api_objects.help_centre_objects.ArticleAttachment,
AttributeError: module 'zenpy' has no attribute 'lib'
```
It triggers when you trying to import file, that imports Zenpy:
```
from zenpy import Zenpy
```

**Comment by facetoe** [comment]
I haven't been able to replicate this issue. Do you have a file called `zenpy.py` anywhere in the import path?

**Comment by super-oleg** [comment]
Of course I don't

**Comment by facetoe** [comment]
Until I can trigger this bug I'd rather not merge this PR, I'm sure you understand. If you can't post the exact code that triggers it, are you able to create a snippet of dummy code that triggers it? I want to understand where it is failing before trying to fix it.

**Pull request closed without merging**
