### PR TITLE
Allow to delete and redact attachments

### LINKED ISSUE #350: Expand AttachmentApi to support deletion and redaction
It would be awesome if this library supported the delete (https://developer.zendesk.com/rest_api/docs/support/attachments#delete-upload) and redact comment attachment (https://developer.zendesk.com/rest_api/docs/support/attachments#redact-comment-attachment) calls.

### PR DESCRIPTION
**Pull request by nerg4l**
Resolves #350

Regarding tests, unfortunately, I could not figure out how to add related tests.

### CODE REVIEW

**Comment by cryptomail** [comment]
https://github.com/facetoe/zenpy/pull/637#issuecomment-2297161278 FYI 
Hang tight.

**Comment by cryptomail** [comment]
ok I can start looking at this now

**Comment by cryptomail** [comment]
I am superceding this PR with https://github.com/facetoe/zenpy/pull/643

**Comment by cryptomail** [comment]
I need to ensure the redaction endpoint works with tests.

**Comment by nerg4l** [comment]
If you could share some additional information or an example PR, then I can provide tests next time. For me at least, the current tests are not easily understandable.

**Comment by cryptomail** [comment]
Got you covered.

**Pull request closed without merging**
