### PR TITLE
More docs

### PR DESCRIPTION
**Pull request by insspb**
@facetoe project has some problem with docs generation on http://docs.facetoe.com.au
Docs are outdated and changes from repo not shown there. Please investigate.

### CODE REVIEW

**Comment by facetoe** [comment]
Yea the docs generation is manual. I should hook it up so Travis updates the docs on release.

**Comment by facetoe** [comment]
Thanks!

**Comment by facetoe** [comment]
Hey when we get that final PR merged I'll regenerate the docs and create a new release.

**Comment by insspb** [comment]
> Yea the docs generation is manual. I should hook it up so Travis updates the docs on release.

When you will add doc gen after pull request accept it is good idea to apply coverage checking too. 
I do not understand how to write test for this project and it is not documented anywhere, but I think tests matter anyway.

**Pull request merged**
